package my.uum;

/**
 * This class is for before the game start
 *
 * @author H'ng Zi Ling 281895
 */
public class A {

    static String a;        // Secret number
    static A nil = new A(); // Object

    /**
     * This method is for generating a secret number.
     * @return 4 digit secret number generated by system randomly.
     */
    public static String get_a() {
        do {
            a = String.valueOf((int) (Math.random() * (9999 - 123 + 1) + 123));
            for (int i = 0; i < a.length(); i++) {
                for (int k = i + 1; k < a.length(); k++) {
                    if (a.length() == 3)
                        a = "0" + a;
                    if (a.charAt(i) == a.charAt(k))
                        a = "invalid";
                }
            }
        } while (a == "invalid");
        return nil.a;
    }

    /**
     * This method is for displaying a menu
     */
    public void disp_a() {
        System.out.printf("\n--------------------MENU--------------------\n" +
                "1 - Start the game\n" +
                "2 - Rule of the 4A0B game\n" +
                "3 - View score\n" +
                "4 - Exit game\n" +
                "Select a number from menu (1-4): ");
    }
}
